FROM dependencytrack/bundled:latest

# Set environment variable to allow iframe embedding
# ENV JAVA_OPTS="-Dowasp.dependency.track.csp.frame-ancestors='self' http://localhost https://localhost"
# RUN mkdir -p /data
# COPY application.properties ./application.properties

EXPOSE 8080